In Python3 range does not return a list
Now Pygam can be run on Python3(tested on Debian 9 with Python 3.5) without any problem;
It would return:
...
TypeError: 'range' object does not support item assignment

before.